### ISSUE TITLE
curwidth & height

### ISSUE THREAD

**Issue by aferriss** [RobinDavid/LSB-Steganography#1] opened 2014-11-16 00:57 UTC
Hi,

I think the curwidth and curheight and reversed on line 34 and line 40...?

switched them and seems to be working fine for me now. Thanks!

**Comment by JackChin** [comment] 2015-07-25 16:00
Ok, someone has already mentioned this problem.

**Comment by Buggaboo** [comment] 2015-07-29 16:03
I fixed this issue in my pull request #4, I've coded against opencv version 2.4.11_1.

Indeed. The indices height and width were mixed up. I don't know if this changed >2.4.11_1 or <2.4.11_1.

Can someone verify?

**Comment by pabloriutort** [comment] 2015-10-08 14:30
Tried both versions and I got the same error as @aferriss using @RobinDavid's version and Ubuntu:
```
OpenCV Error: One of arguments' values is out of range (index is out of range) in cvPtr2D, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/array.cpp, line 1797
Traceback (most recent call last):
  File "script.py", line 8, in <module>
    steg.hideImage(imagetohide)
  File "/home/pablo/Proyectos/LSB-Steganography-master/LSBSteg.py", line 145, in hideImage
    self.putBinaryValue(self.byteValue(int(val)))
  File "/home/pablo/Proyectos/LSB-Steganography-master/LSBSteg.py", line 56, in putBinaryValue
    val = list(self.image[self.curwidth,self.curheight]) #Get the pixel value as a list
cv2.error: index is out of range
```

Images used were [this](https://courses.cit.cornell.edu/ee475/BruceDesign/Mica.datapath.gif) to hide on [this one](http://www.emuseo.org/ssp_director/p.php?a=ZXt3c2FvVGBhf3ljZ1sxOzEkfHduJzg0Nyo4ODAiKyQgIjE%2FOicqMSY6LiY0LT4yJiYrOSc%2FLjI2&m=1331059363). First was changed from .gif to .jpg.

Finally, I downloaded [this blob](https://github.com/Buggaboo/LSB-Steganography/blob/dev/LSBSteg.py) from @Buggaboo's pull request and it works perfectly :+1:

**Comment by RobinDavid** [comment] 2015-10-08 19:02
Hi @pabloriutort ! I have just merged the pull request from @Buggaboo to fix the first issue. For the second I guess this is the numpy running under the hood that is raising the `MemoryError` but I couldn't get to understand why. Does your image were especially big ?

**Comment by pabloriutort** [comment] 2015-10-08 21:28
Hello @RobinDavid. The image is now attached to this comment, but you can also find it on my previous comment. And yes, the image is pretty big with 1,24 MB (maybe another issue?).

If the issue is now solved, feel free to reject my pull request.

![p](https://cloud.githubusercontent.com/assets/5110926/10380406/ec81b712-6e13-11e5-81fa-7de2b672c321.jpg)

**Comment by RobinDavid** [comment] 2017-09-07 09:55
Problem now fixed with refactoring

**Closed by RobinDavid** 2017-09-07 09:55 UTC
